export const initState = {
    singleUser : [],
    register : [],
    userUpdate : [],
    userDelete : [],
    userPosts : [],
    postSingle : [],
    postAdd : [],
    postUpdate : [],
    postDelete : [],
    userSocial : [],
    socialAdd : [],
    socialUpdate : [],
    socialDelete : [],
    userLikes : [],
    likeAdd : [],
    likeDelete : [],
    userComments : [],
    commentAdd : [],
    commentUpdate : [],
    commentDelete : [],
    posts : [{id:1,title:"a1",content:"a2"}],
    postSearch : [],
    userSearch : [],
    info : ""
}